### ISSUE TITLE
how to define the words inside the vocab_attr.txt?

### ISSUE THREAD

**Issue by marcusau** [wavewangyue/ner#1]
Hi ,

   Thanks for your amazing works. I agree with your point very much : For ner task with too many ner classes, we should use multi-task to identify BIOS and NER classes.

   In your codes, I appreciate your vocab_attr.txt very much.  If i have my own dataset, how to define the words to be put into this txt file? 

    I focus on extracting financial related entities with my dataset.

    Thanks a lot.

Marcus

**Comment by wavewangyue** [comment]
vocab_attr.txt containers all NER classes and a "null" class used for padding. I think you can replace them with NER classes in your own dataset. Maybe in financial scene, there are classes like "Company", "InsuranceProduct", etc.
