### ISSUE TITLE
chinese_L-12_H-768_A-12.ckpt文件是哪一个？

### ISSUE THREAD

**Issue by liuyunxing91** [wavewangyue/ner#2]
你好，因为是小白所以诸多不懂，想问一下chinese_L-12_H-768_A-12.ckpt文件是从哪里得到的？从bert项目中下载下来的是一个压缩包，包含如下文件，请问作者您使用的是哪个呢？
![image](https://user-images.githubusercontent.com/29481728/93074599-2fd29780-f6b7-11ea-99c7-6b85d9b8aea1.png)

**Comment by zhengkai215** [comment]
> 你好，因为是小白所以诸多不懂，想问一下chinese_L-12_H-768_A-12.ckpt文件是从哪里得到的？从bert项目中下载下来的是一个压缩包，包含如下文件，请问作者您使用的是哪个呢？
> ![image](https://user-images.githubusercontent.com/29481728/93074599-2fd29780-f6b7-11ea-99c7-6b85d9b8aea1.png)

bert_ckpt_path = "./chinese_L-12_H-768_A-12/bert_model.ckpt" 
这样就行了

**Comment by wavewangyue** [comment]
正解
